openapi: 3.0.0
info:
  title: API BFF - VARU
  version: 1.0.0
  description: API Gateway dos microservi칞os (Invent치rio, Usu치rios e Pedidos)

servers:
  - url: http://192.168.0.104:8080
    description: Servidor BFF

paths:
  /inventario:
    get:
      summary: Retorna itens do invent치rio
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "游닍 Microservi칞o de Invent치rio ativo!"
  
  /usuarios:
    get:
      summary: Retorna lista de usu치rios
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "游녻 Microservi칞o de Usu치rios ativo!"

  /pedidos:
    get:
      summary: Retorna pedidos
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                example:
                  message: "游 Microservi칞o de Pedidos ativo!"
